version: '3'
services:
  api:
    build: ./api
    links:
      - database
    ports:
      - "5000:5000"
    volumes:
      - .:/api
  database:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: dnaVariants
    ports:
      - "3306:3306"
    volumes:
    - .:/database

