version: '3'
services:
  database:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: dnaVariants
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3306:3306"
    volumes:
      - .:/database
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    build: ./api
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306

networks:
  default:
    external:
      name: dataintegration




